Handle the address and size parameters better
Instead of atoi() which has no error handling, switch to strtoul()
so failures will return 0 and check the acceptable size and
address ranges.

Tested:
peci_cmds ping -a 0x30
Succeeded
peci_cmds ping -a 0x20
ERROR: Invalid address "0x20"

peci_cmds RdPCIConfigLocal 0 0 0 -s 1
   cc:0x40 0x86
peci_cmds RdPCIConfigLocal 0 0 0 -s 3
ERROR: Invalid size "3"

Change-Id: Id42e170844a803122669455db6373201e0624a9c
Signed-off-by: Jason M. Bills <jason.m.bills@linux.intel.com>